name: QA

on: [push]

jobs:
  analysis:
    name: analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: phpcs:3.10, php-cs-fixer:3.64, phpstan:2.0.1
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install composer dependencies
        run: composer install --no-progress --prefer-dist --no-dev

      - name: Check coding style with phpcs
        run: |
          phpcs --version
          phpcs

      - name: Check coding style with php-cs-fixer
        run: php-cs-fixer fix --dry-run --show-progress=dots --diff -vv

      - name: Run static analysis
        run: |
          phpstan --version
          phpstan --verbose --error-format=github

  testrun:
    name: run with phpunit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, bcmath, xdebug
          tools: phpunit:11.4
          coverage: xdebug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install composer dependencies
        run: composer install --no-progress --prefer-dist --no-dev

      - name: Run tests
        run: phpunit
