name: QA

on: [push]

jobs:
  analysis:
    name: analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: phpcs:3.7, php-cs-fixer:3.16, phpstan:1.10
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install composer dependencies
        run: composer install --no-progress --prefer-dist --no-dev

      - name: Check coding style with phpcs
        run: phpcs

      - name: Check coding style with php-cs-fixer
        run: php-cs-fixer fix --dry-run --show-progress=dots --diff -vv

      - name: Run static analysis
        run: phpstan --verbose --error-format=github

  testrun:
    name: run with phpunit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, bcmath, xdebug
          tools: phpunit:10.1
          coverage: xdebug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install composer dependencies
        run: composer install --no-progress --prefer-dist --no-dev

      - name: Run tests
        run: phpunit
